# scrape_PMC  
A set of tools to automate image and pdf downloads from pub med central.  

#### Contents: 
1. <a href= #about>About</a>
2. <a href = #.py>scrape_PMC.py</a>  
  a. requirements  
  b. usage   
  c. limitations
3. <a href = #.r>scrape_PMC.r</a>  
  a. requirements  
  b. usage  
  c. limitations

## <a id='about'></a>1. About 
scrape_PMC.py and it's cousin scrape_PMC.r are a set of functions to retrieve PMC ids, download article metadata, figures, and pdfs, given a valid searchterm. The defualt usage downloads article pdfs, metadata, and figures (and captions) and saves them in subfolders.
The python implementation (python3) is a command line program accepting arguments to limit the search and control output.
Note that NCBI explicitly prohibits paralell requests when using their services so please do not abuse their servers.
You may also consider running the program after hours if your id list is long.
 This tool isn't perfect and is bound to miss things, especially older articles where the formatting of the pmc html is different.
 Suggestions for improvements to the flexibility of the scrape are welcomed.
## <a id='.py'></a>2. scrape_PMC.py  
### a. requirements 
  1. `python3.6.X` or greater
  2. <a href='https://www.crummy.com/software/BeautifulSoup/'>`beautifulsoup4`</a> (comes with anaconda distro)  
### b. usage  
`python scrape_PMC.py searchterm --max_retrieve --min_date --max_date --ids_only --pdfs_only --dump_mode --quiet`  
`searchterm`: a valid PMC search term. See <a href=#advanced>'constructing advanced search terms'</a> for complex searches.  
`--max_retrieve`: the maximum number of matching articles to retrieve. Default = 20. Article list is ranked by relevance to search term.  
`--min_date`: oldest publication date limit. must be used with `--max_date`.  
`--max_date`: newest publication date limit. must be used with `--min_date`.  
`--pdfs_only`: only output pdfs, not figures.  
`--dump_mode`: save pdfs to current working directory (won't create sub directories). Can only be used with `--pdfs_only`.  
`--quiet`: only output errors to std out.
